# Generated by Django 5.1.6 on 2025-02-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shortcut', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assings', to='join_app.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dueDate', models.DecimalField(decimal_places=2, max_digits=30)),
                ('position', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prio', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('assignTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='join_app.assign')),
                ('subtasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='join_app.subtask')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contacts', models.ManyToManyField(related_name='users', to='join_app.contact')),
                ('tasks', models.ManyToManyField(related_name='users', to='join_app.task')),
            ],
        ),
    ]
