# Generated by Django 5.1.6 on 2025-02-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
