# Generated by Django 5.1.6 on 2025-03-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_usercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='custom_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
