# Generated by Django 5.1.6 on 2025-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_alter_subtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignTo',
            field=models.ManyToManyField(blank=True, related_name='tasks_list', to='join_app.usercontact'),
        ),
    ]
