# Generated by Django 5.1.6 on 2025-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_alter_task_assignto_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignTo',
        ),
        migrations.AddField(
            model_name='task',
            name='assignTo',
            field=models.ManyToManyField(related_name='tasks', to='join_app.contact'),
        ),
    ]
