# Generated by Django 5.1.6 on 2025-03-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
    ]
