# Generated by Django 5.1.6 on 2025-03-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_remove_task_assignto_task_assignto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
