# Generated by Django 5.1.6 on 2025-03-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_alter_usercontact_contact_alter_usercontact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='usercontact',
            name='custom_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='custom_shortcut',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
