# Generated by Django 5.1.6 on 2025-03-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0006_alter_subtask_task_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='custom_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='custom_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='custom_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='custom_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='custom_shortcut',
            new_name='shortcut',
        ),
    ]
