# Generated by Django 5.1.6 on 2025-03-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0009_alter_task_prio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent', 'Urgent')], max_length=20),
        ),
    ]
