# Generated by Django 5.1.6 on 2025-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0010_alter_task_prio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignTo',
            field=models.ManyToManyField(related_name='tasks_list', to='join_app.usercontact'),
        ),
    ]
